@startuml

title "Prohlížení historie hojení rány"

actor SES as "Ošetřující"
participant MOB as "ZUNI Mobile"
participant SER as "ZUNI Server"
participant PAC as "Evidence Pacientů"
participant RAN as "Evidence Ran"
participant MAT as "Evidence Materiálu"
participant MED as "Úložiště médií"

SES -> MOB: Údaje o pacientovi
note over MOB #a0a0a0
…… stejné jako v případě existující rány ……
end note
SES <- MOB: Seznam pacientů

SES -> MOB: Volba pacienta
note over MOB #a0a0a0
…… stejné jako v případě existující rány ……
end note
SES <- MOB: Seznam ran a jejich posledních stavů

SES -> MOB: Volba rány
SES -> MOB: Prohlédnout historii
MOB -[#5c9807]> SER: (HTTPS)  Načtení historie ošetření rány
SER -> RAN: Načtení historie ošetření rány <font color="red"><size:22>❼
SER <- RAN: Historie ošetření rány
MOB <[#5c9807]- SER: (HTTPS)  Historie ošetření rány
SES <- MOB: Historie ošetření rány

note over MOB, SER
Pokud jsou k historii připojené i obrázky,
aplikace si je postupně načítá a ukazuje uživateli
end note

MOB -[#5c9807]> SER: (HTTPS)  Načíst obrázek
SER -> MED: Načtení obrázku <font color="red"><size:22>❽
SER <- MED: Obrázek
MOB <[#5c9807]- SER: (HTTPS)  Obrázek
SES <- MOB: Obrázek

@enduml
