@startuml

class Uživatel {
    jmeno
    prijmeni
    login
    -- <i>atd...</i> --
}

class Pacient {
    id_pacienta
    jmeno
    prijmeni
    cislo_pojistence
    .. <i>a dále např.</i> ..
    RID
    rizikove_faktory
    luzkove_oddeleni
}


class Návštěva {
    id_navstevy
    datum_cas
}

class Ošetření {
    id_osetreni
    .. <i>stav rány</i> ..
    rozsah_exsudace
    typ_exsudace
    zapach
    okraje_rany
    okoli_rany
    barva_na_spodine
    stav_rany
    hloubka
    sirka
    delka
    poznamka
    .. <i>a dále např.</i> ..
    datum_pristiho_prevazu
    pouzity_material
    rana_zhojena
}

class Materiál {
    id_materialu
    nazev
    mnozstvi
    jednotky
    sarze
    exspirace
}

class Rána {
    id_rany
    nazev_rany
    datum_cas_zalozeni
    poloha
    typ_rány
    .. <i>a dále např.</i> ..
    puvod_rany
    datum_zhojeni
}

class Snímek {
    jpeg / mpeg / DICOM
}

note right
  Vlastní data jsou typicky odesílána do PACS. 
  Jinam se posílají pouze odkazy na serii DICOM snímků
end note

Pacient "1" *-- "*" Rána
Návštěva "1" *-- "*" Ošetření
Ošetření "*" -up-> "1" Rána
Ošetření "1" --> "*" Snímek
Ošetření "1" *..right..> "*" Materiál
Návštěva "*" -up-> "1" Uživatel: ošetřující
Návštěva "*" -up-> "1" Pacient: pacient

hide empty methods    

@enduml
